theme: jekyll-theme-hacker
title: Alexander Barnes
description: The portfolio and resources from Alexander Barnes!
baseurl: /Home/
navigation:
  - title: Home
    url: /Home/
  - title: Games
    url: /games/
