theme: jekyll-theme-leap-day
title: Alexander Barnes
description: The portfolio and resources from Alexander Barnes!
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
navigation:
  - title: Home
    url: /
  - title: Games
    url: /games/
